- hosts: all
  remote_user: vagrant
  become: yes
  become_user: root
  vars_files:
    - /vagrant/provision/ansible/default.yml
    - /vagrant/vm.yml
  roles:
    - { role: repositories  }
    - { role: common        }
    - { role: update,       when: PROVISION.update == 1 }
    - { role: disk          }
    - { role: docker,       when: PROVISION.docker == 1 }
    - { role: ssh           }
    - { role: samba,        when: PROVISION.samba == 1 }
    - { role: php,          when: PROVISION.php == 1 }
    - { role: ntp,          when: PROVISION.ntp == 1 }
    - { role: mail,         when: PROVISION.mail == 1 }
    - { role: firewall       }
    - { role: dnsmasq,      when: PROVISION.dnsmasq == 1 }
    - { role: clitools,     when: PROVISION.clitools == 1 }
    - { role: monit          }
    - { role: desktop,      when: PROVISION.desktop != 0 }
    - { role: user           }
    - { role: docker-dory,  when: PROVISION.dockerDory == 1 }
    - { role: consul,       when: PROVISION.consul == 1 }
    - { role: customization  }
    - { role: finalize       }
